### PR TITLE
Additional round of comments

### PR DESCRIPTION
**Pull request by reneehlozek**
These edits incorporate comments from Renee Hlozek, [Saurabh Jha](https://github.com/aimalz/proclam/issues/70) and Tina Peters.
They include smoothing of the results section and more punchy discussion to make sure that people know what the results of our paper actually are.

A final check must be that the metrics paper matches the metrics code given on the Kaggle page. I will do this once it is updated by Sohier tomorrow.

### CODE REVIEW

**Comment by reneehlozek** [comment]
hi @aimalz I've merged my two branches and checked that they can successfully merge with issue/65 - can you review or let me know the sections I should be paying attention to?

Then I can move on to the [final issues](https://github.com/aimalz/proclam/issues/73) - the largest of which is making sure the draft matches the metric used for the challenge.

**Comment by aimalz** [comment]
The reason that the merge "works" is that some of the text is duplicated, as if previous merge conflicts were resolved by including both versions one after another for every block of conflicting text.  The redundant text makes it not read like a paper anymore, and there were some typos that cause it to fail to even compile.  

I've been reviewing the changes for the last few hours to figure out which text blocks correspond to one another and eliminating the one that's not as clear.  However, I have a long way to go and will not be able to clean this up by the end of the day, and trying for tomorrow morning would also be ill-advised.  

It sounds like a bigger problem if the challenge doesn't end up using anything remotely similar to the metric that we decided upon by way of a careful scientific investigation.  While the paper and the challenge announcement should be synchronized on arXiv, I think there's a good argument for delaying both so our efforts are not wasted.

**Comment by reneehlozek** [comment]
hi @aimalz I have incorporated the changes here: https://github.com/aimalz/proclam/issues/73, the paper still needs final review/checking/editing but I pulled a fresh version of the RH\_editing branch and there remain no conflicts on this PR. At some point it would be useful to merge it so that we can close it.

**Comment by aimalz** [comment]
@reneehlozek I painstakingly reconciled the changes from your "finalized" branch as requested, only to discover upon completion that you'd pushed further changes after telling me to move forward.  I tried my best to incorporate the individual edits without reintroducing duplicated text and compilation bugs, but there's only so much time I can spend combing through diffs over and over again.  If you have any more last-minute requests, please make an issue for them.

**Comment by aimalz** [comment]
Sure enough, there was a bug impeding compilation due to post-hoc editing.  It has now been fixed.

**Pull request merged**
