### PR TITLE
MIT license: yay or nay?

### PR DESCRIPTION
**Pull request by aimalz**
By popular request, I'm adding a license to the repo, just the standard MIT license plus a line about citing us.  If you have objections or comments, reply to this PR by 5 PM EDT on Friday, 19 October 2018.  Otherwise, I'll add the names of all collaborators in the repository and merge it in.

### CODE REVIEW

**Review by emilleishida — APPROVED** [review]

**Comment by AshishMahabal** [comment]
Licenses can be a bit of a thorny issue when they are written at institutions (or by people at institutions). I like the most open GPL. LSST (DM/stack) also uses that, but MIT license is indeed the most open.

GPL may be good because companies can not then incorporate code and develop off of it.

An alternative is to keep it MIT for this and successive challenges, except the last one which can be GPL.

Just some thoughts ...

**Review by cnsetzer — APPROVED** [review]

**Comment by rbiswas4** [comment]
@aimalz Can you please ask Seth Digel if the publication board has anything to say. I seem to recall they preferred BSD 3 clause, but could not find the doc when I looked today. It might be nice to have some uniformity in these packages. Other than this, yay for MIT.

**Comment by gnarayan** [comment]
I'm all for MIT.

**Comment by reneehlozek** [comment]
go go gadget

**Comment by aimalz** [comment]
My merge message seems to have vanished, but the deal is that because this isn't an official DESC code (i.e. to be integrated into a pipeline), contains no original math (all our metrics were invented by others far in the past), and has basically no potential for profit anyway (due to being inefficient for demonstrative/pedagogical purposes), I'm going to go with the default MIT license, with the extra clause about citing the repo in papers.  I added to the copyright statement everyone who ever contributed code, either to the master branch or other branches.  Please let me know if I missed anyone.

**Pull request merged**
