### PR TITLE
Classifier results based on confusion matrix (also improved true class histogram in pipeline)

### PR DESCRIPTION
**Pull request by juramaga**
Just made the histogram bins compatible with integer ids.

### CODE REVIEW

**Comment by aimalz** [comment]
Thanks for improving the plot!  I'm going to rename this PR, though, since the introduction of the confusion matrix-based classifier is a much more major change that requires more thorough review.

**Comment by aimalz** [comment]
I added some tests of this into the pipeline notebook and made some other minor changes.  @juramaga I can approve the PR if you're happy with it.

**Comment by juramaga** [comment]
I am happy with your changes, Alex.

**Review by aimalz — APPROVED** [review]
No obvious problems here

**Pull request merged**
